name: Build, Test and Deploy

on:
  push:
    branches:
      - main
env:
  JDBC_DATABASE_URL: ${{ secrets.JDBC_DATABASE_URL }}
  JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD }}
  JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with maven
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build project
      run: |
        mvn -B -DskipTests clean install
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Run tests
      run: |
        mvn test
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Ubuntu Server
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          bash deploy.sh
